ALTER TABLE solicitudes
ADD COLUMN IF NOT EXISTS tramo_lat_ini DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS tramo_lng_ini DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS tramo_lat_fin DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS tramo_lng_fin DOUBLE PRECISION;
